// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of one tool call executing inside a bridged external agent core.
 */
export type BridgeToolActivityStatus = "started" | "completed" | "failed";
