// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeToolActivityStatus } from "./BridgeToolActivityStatus";

/**
 * Live status of one tool call executing inside a bridged external agent
 * core (the ZCode warm bridge). Display only: the tool ran on the far side
 * of the bridge, so it has no matching item in the thread history.
 */
export type BridgeToolActivityNotification = { threadId: string, turnId: string,
/**
 * The external core's id for the tool call.
 */
callId: string, tool: string, status: BridgeToolActivityStatus,
/**
 * Bounded human-readable detail (input summary, output preview, or
 * error message), capped by the bridge before emission.
 */
detail: string | null, };
